services:
  postgres:
    image: postgres:16
    container_name: regulatrack_postgres
    environment:
      POSTGRES_DB: regulatrack
      POSTGRES_USER: regulatrack
      POSTGRES_PASSWORD: regulatrack
    ports:
      - "5433:5432"
    volumes:
      - regulatrack_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regulatrack -d regulatrack"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: regulatrack_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build:
      context: ./backend
    container_name: regulatrack_backend
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/regulatrack
      SPRING_DATASOURCE_USERNAME: regulatrack
      SPRING_DATASOURCE_PASSWORD: regulatrack
      SERVER_PORT: 8080
      APP_SEED_ENABLED: true
      APP_FRONTEND_BASE_URL: http://localhost:4200
      APP_MAIL_ENABLED: true
      APP_MAIL_FROM: no-reply@regulatrack.local
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_SMTP_AUTH: false
      MAIL_STARTTLS: false
    volumes:
      - regulatrack_documents:/app/storage/documents
    ports:
      - "8083:8080"

volumes:
  regulatrack_pgdata:
  regulatrack_documents:


