package com.regulatrack.backend.domain.user;

public enum Permission {
    DASHBOARD_VIEW,
    LICENSES_VIEW, LICENSES_CREATE, LICENSES_UPDATE, LICENSES_DELETE,
    LICENSE_DOCUMENT_VIEW, LICENSE_DOCUMENT_UPLOAD, LICENSE_DOCUMENT_DELETE,
    COMPANIES_VIEW, COMPANIES_CREATE, COMPANIES_UPDATE, COMPANIES_DELETE,
    BRANCHES_VIEW, BRANCHES_CREATE, BRANCHES_UPDATE, BRANCHES_DELETE,
    USERS_VIEW, USERS_CREATE, USERS_UPDATE, USERS_DELETE
}
