spring.application.name=regulatrack

# =========================
# DATABASE (DOCKER)
# =========================
spring.datasource.url=jdbc:postgresql://postgres:5432/regulatrack
spring.datasource.username=regulatrack
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true

# =========================
# SEED (IMPORTANTE)
# =========================
app.seed.enabled=true