spring.application.name=regulatrack

spring.datasource.url=jdbc:postgresql://localhost:5432/regulatrack
spring.datasource.username=regulatrack
spring.datasource.password=regulatrack
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080
